# Generated by Django 4.1.7 on 2023-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leagues",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("sport_id", models.TextField()),
                ("section_id", models.TextField()),
                ("slug", models.TextField()),
                ("name_translations", models.JSONField()),
                ("has_logo", models.BooleanField()),
                ("logo", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("priority", models.TextField()),
                ("host", models.JSONField()),
                ("tennis_points", models.TextField()),
                ("facts", models.JSONField()),
                ("most_count", models.TextField()),
                ("section", models.JSONField()),
                ("sport", models.JSONField()),
            ],
        ),
    ]
