# Generated by Django 4.1.7 on 2023-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagues",
            name="end_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="facts",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="has_logo",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="host",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="logo",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="most_count",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="name_translations",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="priority",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="section",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="slug",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="sport",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="start_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leagues",
            name="tennis_points",
            field=models.TextField(null=True),
        ),
    ]
