# Generated by Django 4.1.7 on 2023-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0002_alter_leagues_end_date_alter_leagues_facts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("home_team_id", models.TextField(null=True)),
                ("away_team_id", models.TextField(null=True)),
                ("challenge_id", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("start_at", models.TextField(blank=True, null=True)),
                ("home_team", models.JSONField(null=True)),
                ("away_team", models.JSONField(null=True)),
                ("home_score", models.JSONField(null=True)),
                ("away_score", models.JSONField(null=True)),
                ("main_odds", models.JSONField(null=True)),
                ("winner_code", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
