# Generated by Django 4.1.7 on 2023-03-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0003_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="aggregated_winner_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="attendance",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="cards_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="coverage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="cup_match_in_round",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="cup_match_order",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="default_period_count",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="event_data_change",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="first_supply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="ground_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="lasted_period",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="league_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="medias_count",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="periods",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="periods_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="priority",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="referee_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="result_only",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="round_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="round_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="season_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="series_count",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="sport",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="sport_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="status_lineup",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="time_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="venue_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
