# Generated by Django 4.1.7 on 2023-03-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0004_events_aggregated_winner_code_events_attendance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("sport_id", models.TextField(null=True)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("name_translation", models.JSONField(null=True)),
                ("name_short", models.TextField(null=True)),
                ("has_photo", models.BooleanField(null=True)),
                ("photo", models.TextField(null=True)),
                ("position", models.TextField(null=True)),
                ("position_name", models.TextField(null=True)),
                ("weight", models.TextField(null=True)),
                ("age", models.TextField(null=True)),
                ("date_birth_at", models.DateField(null=True)),
                ("height", models.TextField(null=True)),
                ("shirt_number", models.TextField(null=True)),
                ("preferred_foot", models.TextField(null=True)),
                ("nationality_code", models.TextField(null=True)),
                ("flag", models.TextField(null=True)),
                ("market_currency", models.TextField(null=True)),
                ("market_value", models.TextField(null=True)),
                ("contract_until", models.TextField(null=True)),
                ("rating", models.TextField(null=True)),
                ("characteristics", models.JSONField(null=True)),
                ("positions", models.JSONField(null=True)),
                ("ability", models.JSONField(null=True)),
                ("main_team", models.JSONField(null=True)),
            ],
        ),
    ]
