# Generated by Django 4.1.7 on 2023-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0005_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="date_birth_at",
            field=models.TextField(blank=True, null=True),
        ),
    ]
