# Generated by Django 4.1.7 on 2023-03-26 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0006_alter_players_date_birth_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="players",
            old_name="name_translation",
            new_name="name_translations",
        ),
    ]
