# Generated by Django 4.1.7 on 2023-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0008_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="challenge",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="league",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="season",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="section",
            field=models.JSONField(null=True),
        ),
    ]
