# Generated by Django 4.1.7 on 2023-04-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0009_events_challenge_events_league_events_season_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="round_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
