# Generated by Django 4.1.7 on 2023-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0010_alter_events_round_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("data", models.JSONField(null=True)),
            ],
        ),
    ]
