# Generated by Django 4.1.7 on 2024-02-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0013_icehockeyevents"),
    ]

    operations = [
        migrations.CreateModel(
            name="TennisTournaments",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("sport_id", models.TextField()),
                ("section_id", models.TextField()),
                ("slug", models.TextField(null=True)),
                ("name_translations", models.JSONField(null=True)),
                ("has_logo", models.BooleanField(null=True)),
                ("logo", models.TextField(null=True)),
                ("start_date", models.TextField(blank=True, null=True)),
                ("end_date", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(null=True)),
                ("host", models.JSONField(null=True)),
                ("tennis_points", models.TextField(null=True)),
                ("facts", models.JSONField(null=True)),
                ("most_count", models.TextField(null=True)),
                ("section", models.JSONField(null=True)),
                ("sport", models.JSONField(null=True)),
            ],
        ),
    ]
