# Generated by Django 4.1.7 on 2024-02-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0014_tennistournaments"),
    ]

    operations = [
        migrations.CreateModel(
            name="TennisEvents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("home_team_id", models.TextField(null=True)),
                ("away_team_id", models.TextField(null=True)),
                ("challenge_id", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("start_at", models.TextField(blank=True, null=True)),
                ("home_team", models.JSONField(null=True)),
                ("away_team", models.JSONField(null=True)),
                ("home_score", models.JSONField(null=True)),
                ("away_score", models.JSONField(null=True)),
                ("main_odds", models.JSONField(null=True)),
                ("winner_code", models.TextField(blank=True, null=True)),
                ("sport_id", models.TextField(blank=True, null=True)),
                ("league_id", models.TextField(blank=True, null=True)),
                ("season_id", models.TextField(blank=True, null=True)),
                ("venue_id", models.TextField(blank=True, null=True)),
                ("referee_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("time_details", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("aggregated_winner_code", models.TextField(blank=True, null=True)),
                ("result_only", models.TextField(blank=True, null=True)),
                ("coverage", models.TextField(blank=True, null=True)),
                ("ground_type", models.TextField(blank=True, null=True)),
                ("round_number", models.TextField(blank=True, null=True)),
                ("series_count", models.TextField(blank=True, null=True)),
                ("medias_count", models.TextField(blank=True, null=True)),
                ("status_lineup", models.TextField(blank=True, null=True)),
                ("first_supply", models.TextField(blank=True, null=True)),
                ("cards_code", models.TextField(blank=True, null=True)),
                ("event_data_change", models.TextField(blank=True, null=True)),
                ("lasted_period", models.TextField(blank=True, null=True)),
                ("default_period_count", models.TextField(blank=True, null=True)),
                ("attendance", models.TextField(blank=True, null=True)),
                ("cup_match_order", models.TextField(blank=True, null=True)),
                ("cup_match_in_round", models.TextField(blank=True, null=True)),
                ("periods", models.JSONField(null=True)),
                ("round_info", models.JSONField(blank=True, null=True)),
                ("periods_time", models.TextField(blank=True, null=True)),
                ("sport", models.JSONField(null=True)),
                ("league", models.JSONField(null=True)),
                ("challenge", models.JSONField(null=True)),
                ("season", models.JSONField(null=True)),
                ("section", models.JSONField(null=True)),
            ],
        ),
    ]
