# Generated by Django 4.1.7 on 2024-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0015_tennisevents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennistournaments",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
