# Generated by Django 4.1.7 on 2024-06-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sportscore", "0016_alter_tennistournaments_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennistournaments",
            name="start_date",
            field=models.TextField(blank=True, null=True),
        ),
    ]
