# Generated by Django 4.1.7 on 2024-02-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtpTour",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("section_id", models.IntegerField()),
                ("slug", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("tennis_points", models.IntegerField()),
                ("number_of_sets", models.IntegerField()),
                ("surface", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("prize_money", models.IntegerField()),
                ("continent", models.CharField(max_length=255)),
                ("number_of_competitors", models.IntegerField()),
                ("most_count", models.IntegerField()),
            ],
        ),
    ]
