# Generated by Django 4.1.7 on 2024-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0002_alter_atptour_city_alter_atptour_continent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("name_short", models.TextField(null=True)),
                ("name_full", models.TextField(null=True)),
                ("gender", models.TextField(null=True)),
                ("dob", models.DateField(null=True)),
                ("hand", models.TextField(null=True)),
                ("weight", models.TextField(null=True)),
                ("height", models.FloatField(null=True)),
                ("country_code", models.TextField(null=True)),
                ("country", models.TextField(null=True)),
                ("prize_total_euros", models.IntegerField(null=True)),
                ("prize_current_euros", models.IntegerField(null=True)),
            ],
        ),
    ]
