# Generated by Django 4.1.7 on 2024-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0003_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="birthplace",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="residence",
            field=models.TextField(null=True),
        ),
    ]
