# Generated by Django 4.1.7 on 2024-02-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0004_player_birthplace_player_residence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpMatch",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                ("court_time", models.IntegerField(null=True)),
                ("w_ace", models.IntegerField(null=True)),
                ("w_df", models.IntegerField(null=True)),
                ("w_svpt", models.IntegerField(null=True)),
                ("w_firstin", models.IntegerField(null=True)),
                ("w_firstwon", models.IntegerField(null=True)),
                ("w_secondwon", models.IntegerField(null=True)),
                ("w_svgms", models.IntegerField(null=True)),
                ("w_bpsaved", models.IntegerField(null=True)),
                ("w_bpfaced", models.IntegerField(null=True)),
                ("l_ace", models.IntegerField(null=True)),
                ("l_df", models.IntegerField(null=True)),
                ("l_svpt", models.IntegerField(null=True)),
                ("l_firstin", models.IntegerField(null=True)),
                ("l_firstwon", models.IntegerField(null=True)),
                ("l_secondwon", models.IntegerField(null=True)),
                ("l_svgms", models.IntegerField(null=True)),
                ("l_bpsaved", models.IntegerField(null=True)),
                ("l_bpfaced", models.IntegerField(null=True)),
                ("event_id", models.TextField(null=True)),
                ("winner_code", models.TextField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="atp_match",
                        to="tennis_api.atptour",
                    ),
                ),
            ],
        ),
    ]
