# Generated by Django 4.1.7 on 2024-02-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0005_atpmatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atpmatch",
            name="date",
        ),
        migrations.AddField(
            model_name="atpmatch",
            name="start_at",
            field=models.DateTimeField(null=True),
        ),
    ]
