# Generated by Django 4.1.7 on 2024-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0006_remove_atpmatch_date_atpmatch_start_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atpmatch",
            name="match_num",
        ),
    ]
