# Generated by Django 4.1.7 on 2024-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0007_remove_atpmatch_match_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatch",
            name="challenge_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatch",
            name="status",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatch",
            name="status_more",
            field=models.TextField(null=True),
        ),
    ]
