# Generated by Django 4.1.7 on 2024-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0009_atpelohard_atpelograss_atpeloclay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atpmatch",
            name="winner_code",
            field=models.IntegerField(null=True),
        ),
    ]
