# Generated by Django 4.1.7 on 2024-03-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0010_alter_atpmatch_winner_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetAtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_name", models.TextField(null=True)),
                ("away_name", models.TextField(null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("elo_prob", models.FloatField(null=True)),
                ("year_elo_prob", models.FloatField(null=True)),
                ("home_spw", models.FloatField(null=True)),
                ("home_rpw", models.FloatField(null=True)),
                ("away_spw", models.FloatField(null=True)),
                ("away_rpw", models.FloatField(null=True)),
                ("stats_win", models.FloatField(null=True)),
                ("home_fatigue", models.FloatField(null=True)),
                ("away_fatigue", models.FloatField(null=True)),
                ("h2h_win", models.FloatField(null=True)),
                ("h2h_matches", models.IntegerField(null=True)),
                ("walkover_home", models.BooleanField(null=True)),
                ("walkover_away", models.BooleanField(null=True)),
                ("home_inj_score", models.FloatField(null=True)),
                ("away_inj_score", models.FloatField(null=True)),
                ("common_opponents", models.FloatField(null=True)),
                ("common_opponents_count", models.IntegerField(null=True)),
                ("preview", models.TextField(null=True)),
                ("reasoning", models.TextField(null=True)),
                ("start_at", models.DateTimeField(null=True)),
                ("home_prob", models.FloatField(null=True)),
                ("away_prob", models.FloatField(null=True)),
                ("home_yield", models.FloatField(null=True)),
                ("away_yield", models.FloatField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bet_away",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bet_home",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tennis_api.atpmatch",
                    ),
                ),
            ],
        ),
    ]
