# Generated by Django 4.1.7 on 2024-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0011_betatp"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatch",
            name="away_odds",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatch",
            name="home_odds",
            field=models.FloatField(null=True),
        ),
    ]
