# Generated by Django 4.1.7 on 2024-03-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0012_atpmatch_away_odds_atpmatch_home_odds"),
    ]

    operations = [
        migrations.CreateModel(
            name="WtaTour",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("section_id", models.IntegerField()),
                ("slug", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("city", models.TextField(null=True)),
                ("country", models.TextField(null=True)),
                ("tennis_points", models.IntegerField(null=True)),
                ("number_of_sets", models.IntegerField(null=True)),
                ("surface", models.TextField(null=True)),
                ("currency", models.TextField(null=True)),
                ("prize_money", models.IntegerField(null=True)),
                ("continent", models.TextField(null=True)),
                ("number_of_competitors", models.IntegerField(null=True)),
                ("most_count", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WtaMatch",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("court_time", models.IntegerField(null=True)),
                ("w_ace", models.IntegerField(null=True)),
                ("w_df", models.IntegerField(null=True)),
                ("w_svpt", models.IntegerField(null=True)),
                ("w_firstin", models.IntegerField(null=True)),
                ("w_firstwon", models.IntegerField(null=True)),
                ("w_secondwon", models.IntegerField(null=True)),
                ("w_svgms", models.IntegerField(null=True)),
                ("w_bpsaved", models.IntegerField(null=True)),
                ("w_bpfaced", models.IntegerField(null=True)),
                ("l_ace", models.IntegerField(null=True)),
                ("l_df", models.IntegerField(null=True)),
                ("l_svpt", models.IntegerField(null=True)),
                ("l_firstin", models.IntegerField(null=True)),
                ("l_firstwon", models.IntegerField(null=True)),
                ("l_secondwon", models.IntegerField(null=True)),
                ("l_svgms", models.IntegerField(null=True)),
                ("l_bpsaved", models.IntegerField(null=True)),
                ("l_bpfaced", models.IntegerField(null=True)),
                ("event_id", models.TextField(null=True)),
                ("winner_code", models.IntegerField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("challenge_id", models.IntegerField(null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_away",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_home",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_match",
                        to="tennis_api.wtatour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WtaEloHard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_elo_hard",
                        to="tennis_api.wtamatch",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_elo_hard",
                        to="tennis_api.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WtaEloGrass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_elo_grass",
                        to="tennis_api.wtamatch",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_elo_grass",
                        to="tennis_api.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WtaEloClay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_elo_clay",
                        to="tennis_api.wtamatch",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wta_elo_clay",
                        to="tennis_api.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BetWta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_name", models.TextField(null=True)),
                ("away_name", models.TextField(null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("elo_prob", models.FloatField(null=True)),
                ("year_elo_prob", models.FloatField(null=True)),
                ("home_spw", models.FloatField(null=True)),
                ("home_rpw", models.FloatField(null=True)),
                ("away_spw", models.FloatField(null=True)),
                ("away_rpw", models.FloatField(null=True)),
                ("stats_win", models.FloatField(null=True)),
                ("home_fatigue", models.FloatField(null=True)),
                ("away_fatigue", models.FloatField(null=True)),
                ("h2h_win", models.FloatField(null=True)),
                ("h2h_matches", models.IntegerField(null=True)),
                ("walkover_home", models.BooleanField(null=True)),
                ("walkover_away", models.BooleanField(null=True)),
                ("home_inj_score", models.FloatField(null=True)),
                ("away_inj_score", models.FloatField(null=True)),
                ("common_opponents", models.FloatField(null=True)),
                ("common_opponents_count", models.IntegerField(null=True)),
                ("preview", models.TextField(null=True)),
                ("reasoning", models.TextField(null=True)),
                ("start_at", models.DateTimeField(null=True)),
                ("home_prob", models.FloatField(null=True)),
                ("away_prob", models.FloatField(null=True)),
                ("home_yield", models.FloatField(null=True)),
                ("away_yield", models.FloatField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bet_wta_away",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bet_wta_home",
                        to="tennis_api.player",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tennis_api.wtamatch",
                    ),
                ),
            ],
        ),
    ]
