# Generated by Django 4.1.7 on 2024-03-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0014_atpmatch_away_score_atpmatch_home_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="betatp",
            name="away_stat_matches",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="betatp",
            name="home_stat_matches",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_stat_matches",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_stat_matches",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="wtamatch",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
