# Generated by Django 4.1.7 on 2024-03-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tennis_api",
            "0015_betatp_away_stat_matches_betatp_home_stat_matches_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wtamatch",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
