# Generated by Django 4.1.7 on 2024-03-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_api", "0016_alter_wtamatch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wtaelohard",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wta_elo_hard_player",
                to="tennis_api.player",
            ),
        ),
    ]
