version: "3.9"

services:
  tennisproject:
    container_name: tennisproject
    build:
      context: tennisproject
    volumes:
      - ./tennisproject:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://tennis:tennis@db:5432/tennis?connect_timeout=3
      - DBT_HOST=db
      - DBT_NAME=tennis
      - DBT_USER=tennis
      - DBT_PASSWORD=tennis
      - DJANGO_SUPERUSER_USERNAME=repomi
      - DJANGO_SUPERUSER_EMAIL=repomi@msn.com
      - DJANGO_SUPERUSER_PASSWORD=repomi
      - RUN_MIGRATIONS=true
      - GUNICORN=true
      - SPORT_SCORE_KEY
      - OPENAI_API_KEY
      - ALLOWED_HOSTS=*
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tennis
      POSTGRES_PASSWORD: tennis
      POSTGRES_DB: tennis

  tennis-app:
    image: tennis-app-dev:20230807
    build:
      context: tennis-app
      target: development
    volumes:
      - ./tennis-app:/app
    environment:
      IAM_APP_BASE_URL: http://localhost:4000
      NODE_OPTIONS: --max-old-space-size=1536
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: ${TENNIS_APP_MEMORY_LIMIT:-2048M}
    ports:
      - 2999:3000

  tennis-app-bff:
    build:
      context: tennis-app
      dockerfile: docker/openresty/Dockerfile
    image: tennis-app-openresty:20230405
    volumes:
      - ./tennis-app/docker/openresty/tennis-app.dev.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      SESSION_SECRET: supersecretsession
      UPSTREAM_URL: http://tennis-app:3000
      TENNIS_API_URL: http://tennisproject:8000
      HARDCODED_AUTH_USER_ID: local-dev-user
      HARDCODED_AUTH_EMAIL: admin@example.com
      HARDCODED_AUTH_ROLE: OrganizationAdmin
    restart: unless-stopped
    depends_on:
      - tennis-app
    ports:
      - 3000:80

  tennis-app-bff-noauth:
    build:
      context: tennis-app
      dockerfile: docker/openresty/Dockerfile
    image: tennis-app-openresty:20230405
    volumes:
      - ./tennis-app/docker/openresty/tennis-app.dev.noauth.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      SESSION_SECRET: supersecretsession
      UPSTREAM_URL: http://tennis-app:3000
      TENNIS_API_URL: http://tennisproject:8000
      HARDCODED_AUTH_USER_ID: local-dev-user
      HARDCODED_AUTH_EMAIL: admin@example.com
      HARDCODED_AUTH_ROLE: OrganizationAdmin
    restart: unless-stopped
    depends_on:
      - tennis-app
    ports:
      - 3001:80

volumes:
  postgres_data:
