version: "3.9"

services:
  tennisproject:
    container_name: tennisproject
    build:
      context: tennisproject
    volumes:
      - ./tennisproject:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://tennis:tennis@db:5432/tennis?connect_timeout=3
      - DBT_HOST=db
      - DBT_NAME=tennis
      - DBT_USER=tennis
      - DBT_PASSWORD=tennis
      - DJANGO_SUPERUSER_USERNAME=repomi
      - DJANGO_SUPERUSER_EMAIL=repomi@msn.com
      - DJANGO_SUPERUSER_PASSWORD=repomi
      - RUN_MIGRATIONS=true
      - GUNICORN=true
      - SPORT_SCORE_KEY

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tennis
      POSTGRES_PASSWORD: tennis
      POSTGRES_DB: tennis
  tennis-app:
    image: tennis-app-dev:20230310
    build:
      context: tennis-app
      target: development
    environment:
      IAM_APP_BASE_URL: http://localhost:4000
    volumes:
      - ./tennis-app:/app
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 2048M
  tennis-app-bff:
    build:
      context: tennis-app
      dockerfile: docker/openresty/Dockerfile
    image: tennis-app-openresty:20230405
    volumes:
      - ./tennis-app/docker/openresty/tennis-app.dev.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      SESSION_SECRET: supersecretsession
      UPSTREAM_URL: http://tennis-app:3000
      IAM_APP_BASE_URL: http://localhost:4000
      #METRICS_API_URL: http://metrics-service-apigw
      #METRICS_API_URL: http://metrics-service-oathkeeper:4455
      #OIDC_DISCOVERY_URL: https://dev.dex.surveypal-test.dev/.well-known/openid-configuration
      #OIDC_CLIENT_ID: metrics-dev
      #OIDC_CLIENT_SECRET: metrics-dev
      #OIDC_SCOPE: "openid email profile offline_access"
    restart: unless-stopped
    depends_on:
      - tennis-app
    ports:
      - 3000:80
volumes:
  postgres_data:
