# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes

DISABLE_LINTERS:
  - CSS_SCSS_LINT
  - YAML_V8R

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_ARGUMENTS: --max-warnings=0
TYPESCRIPT_ES_FILE_EXTENSIONS:
  - .ts
  - .tsx

JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_ARGUMENTS: --max-warnings=0

ERROR_ON_MISSING_EXEC_BIT: true
BASH_SHELLCHECK_DISABLE_ERRORS: true

BASH_SHFMT_ARGUMENTS: -i 4

MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true

PRE_COMMANDS:
  - command: gem install json
    cwd: "root" # Will be run at the root of the workspace (usually your repository root)
  - command: yarn install
    cwd: "workspace"
