from django.db import models


# Create your models here.
class Leagues(models.Model):
    id = models.TextField(primary_key=True)
    sport_id = models.TextField()
    section_id = models.TextField()
    slug = models.TextField(null=True)
    name_translations = models.JSONField(null=True)
    has_logo = models.BooleanField(null=True)
    logo = models.TextField(null=True)
    start_date = models.TextField(null=True, blank=True)
    end_date = models.TextField(null=True, blank=True)
    priority = models.TextField(null=True)
    host = models.JSONField(null=True)
    tennis_points = models.TextField(null=True)
    facts = models.JSONField(null=True)
    most_count = models.TextField(null=True)
    section = models.JSONField(null=True)
    sport = models.JSONField(null=True)


class Events(models.Model):
    id = models.TextField(primary_key=True)
    slug = models.TextField(null=True)
    home_team_id = models.TextField(null=True)
    away_team_id = models.TextField(null=True)
    challenge_id = models.TextField(null=True)
    status = models.TextField(null=True)
    status_more = models.TextField(null=True)
    start_at = models.TextField(null=True, blank=True)
    home_team = models.JSONField(null=True)
    away_team = models.JSONField(null=True)
    home_score = models.JSONField(null=True)
    away_score = models.JSONField(null=True)
    main_odds = models.JSONField(null=True)
    winner_code = models.TextField(null=True, blank=True)
    sport_id = models.TextField(null=True, blank=True)
    league_id = models.TextField(null=True, blank=True)
    season_id = models.TextField(null=True, blank=True)
    venue_id = models.TextField(null=True, blank=True)
    referee_id = models.TextField(null=True, blank=True)
    name = models.TextField(null=True, blank=True)
    time_details = models.TextField(null=True, blank=True)
    priority = models.TextField(null=True, blank=True)
    aggregated_winner_code = models.TextField(null=True, blank=True)
    result_only = models.TextField(null=True, blank=True)
    coverage = models.TextField(null=True, blank=True)
    ground_type = models.TextField(null=True, blank=True)
    round_number = models.TextField(null=True, blank=True)
    series_count = models.TextField(null=True, blank=True)
    medias_count = models.TextField(null=True, blank=True)
    status_lineup = models.TextField(null=True, blank=True)
    first_supply = models.TextField(null=True, blank=True)
    cards_code = models.TextField(null=True, blank=True)
    event_data_change = models.TextField(null=True, blank=True)
    lasted_period = models.TextField(null=True, blank=True)
    default_period_count = models.TextField(null=True, blank=True)
    attendance = models.TextField(null=True, blank=True)
    cup_match_order = models.TextField(null=True, blank=True)
    cup_match_in_round = models.TextField(null=True, blank=True)
    periods = models.JSONField(null=True)
    round_info = models.TextField(null=True, blank=True)
    periods_time = models.TextField(null=True, blank=True)
    sport = models.JSONField(null=True)


