config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
tennis_metrics:
  outputs:
    prod:
      dbname: "{{ env_var('DBT_NAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
  target: prod
