# Generated by Django 4.1.7 on 2024-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PremierLeague",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("home_team_id", models.TextField(null=True)),
                ("away_team_id", models.TextField(null=True)),
                ("challenge_id", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("home_team_name", models.TextField(null=True)),
                ("away_team_name", models.TextField(null=True)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                ("winner_code", models.TextField(blank=True, null=True)),
                (
                    "home_odds",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "away_odds",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
