# Generated by Django 4.1.7 on 2024-02-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="premierleague",
            name="draw_odds",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="premierleague",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="challenge_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="winner_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
