# Generated by Django 4.1.7 on 2024-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0002_premierleague_draw_odds_premierleague_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premierleague",
            name="away_odds",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="draw_odds",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="premierleague",
            name="home_odds",
            field=models.FloatField(null=True),
        ),
    ]
