# Generated by Django 4.1.7 on 2024-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0003_alter_premierleague_away_odds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("home_team_id", models.TextField(null=True)),
                ("away_team_id", models.TextField(null=True)),
                ("challenge_id", models.IntegerField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("home_team_name", models.TextField(null=True)),
                ("away_team_name", models.TextField(null=True)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                ("winner_code", models.IntegerField(blank=True, null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("draw_odds", models.FloatField(null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
