# Generated by Django 4.1.7 on 2024-02-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "footballapi",
            "0007_premierelohome_premiereloaway_championshipelohome_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FaCup",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("challenge_id", models.IntegerField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("home_team_name", models.TextField(null=True)),
                ("away_team_name", models.TextField(null=True)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                ("winner_code", models.IntegerField(blank=True, null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("draw_odds", models.FloatField(null=True)),
                ("start_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away_fa_cup_matches",
                        to="footballapi.teams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home_fa_cup_matches",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
    ]
