# Generated by Django 4.1.7 on 2024-02-11 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0010_laligahome_laligaeloaway_laligaelo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LaLigaHome",
            new_name="LaLigaEloHome",
        ),
    ]
