# Generated by Django 4.1.7 on 2024-02-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0011_rename_laligahome_laligaelohome"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerieA",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("challenge_id", models.IntegerField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("home_team_name", models.TextField(null=True)),
                ("away_team_name", models.TextField(null=True)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                ("winner_code", models.IntegerField(blank=True, null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("draw_odds", models.FloatField(null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away_seriea_matches",
                        to="footballapi.teams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home_seriea_matches",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SerieAEloHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_home_seriea",
                        to="footballapi.seriea",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_home_seriea",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SerieAEloAway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_away_seriea",
                        to="footballapi.seriea",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_away_seriea",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SerieAElo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_seriea",
                        to="footballapi.seriea",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_seriea",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
    ]
