# Generated by Django 4.1.7 on 2024-02-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0012_seriea_serieaelohome_serieaeloaway_serieaelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundesliga",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("challenge_id", models.IntegerField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("home_team_name", models.TextField(null=True)),
                ("away_team_name", models.TextField(null=True)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                ("winner_code", models.IntegerField(blank=True, null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("draw_odds", models.FloatField(null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away_bundesliga_matches",
                        to="footballapi.teams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home_bundesliga_matches",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ligue1",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("challenge_id", models.IntegerField(null=True)),
                ("status", models.TextField(null=True)),
                ("status_more", models.TextField(null=True)),
                ("home_team_name", models.TextField(null=True)),
                ("away_team_name", models.TextField(null=True)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                ("winner_code", models.IntegerField(blank=True, null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("draw_odds", models.FloatField(null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away_ligue1_matches",
                        to="footballapi.teams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home_ligue1_matches",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ligue1EloHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_home_ligue1",
                        to="footballapi.ligue1",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_home_ligue1",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ligue1EloAway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_away_ligue1",
                        to="footballapi.ligue1",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_away_ligue1",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ligue1Elo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_ligue1",
                        to="footballapi.ligue1",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_ligue1",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BundesligaEloHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_home_bundesliga",
                        to="footballapi.bundesliga",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_home_bundesliga",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BundesligaEloAway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_away_bundesliga",
                        to="footballapi.bundesliga",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_away_bundesliga",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BundesligaElo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_bundesliga",
                        to="footballapi.bundesliga",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="elo_rating_bundesliga",
                        to="footballapi.teams",
                    ),
                ),
            ],
        ),
    ]
