# Generated by Django 4.1.7 on 2024-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0014_betfootball"),
    ]

    operations = [
        migrations.AddField(
            model_name="betfootball",
            name="level",
            field=models.TextField(null=True),
        ),
    ]
