# Generated by Django 4.1.7 on 2024-03-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballapi", "0016_allleagues"),
    ]

    operations = [
        migrations.AddField(
            model_name="betfootball",
            name="away_est_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="away_poisson",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="draw_poisson",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="home_est_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="home_poisson",
            field=models.FloatField(null=True),
        ),
    ]
