# Generated by Django 4.1.7 on 2024-03-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "footballapi",
            "0017_betfootball_away_est_goals_betfootball_away_poisson_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="betfootball",
            name="away_conceded",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="away_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="home_conceded",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betfootball",
            name="home_goals",
            field=models.FloatField(null=True),
        ),
    ]
