# Generated by Django 4.1.7 on 2023-11-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Combination",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("prob", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
