# Generated by Django 4.1.7 on 2023-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WinShare",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("bets", models.IntegerField()),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Match",
        ),
    ]
