# Generated by Django 4.1.7 on 2023-11-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0002_winshare_delete_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="combination",
            name="bet",
            field=models.BooleanField(default=False),
        ),
    ]
