# Generated by Django 4.1.7 on 2023-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0003_combination_bet"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonivetoProb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prob", models.FloatField()),
                ("score", models.TextField()),
                ("match_nro", models.IntegerField()),
            ],
        ),
    ]
