# Generated by Django 4.1.7 on 2023-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0004_monivetoprob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monivetoprob",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
