# Generated by Django 4.1.7 on 2023-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0005_alter_monivetoprob_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonivetoOdds",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
