# Generated by Django 4.1.7 on 2023-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0006_monivetoodds"),
    ]

    operations = [
        migrations.AddField(
            model_name="monivetoodds",
            name="match1",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="monivetoodds",
            name="match2",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="monivetoodds",
            name="match3",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="monivetoodds",
            name="match4",
            field=models.TextField(default=""),
        ),
    ]
