# Generated by Django 4.1.7 on 2023-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0007_monivetoodds_match1_monivetoodds_match2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monivetoodds",
            name="bet",
            field=models.BooleanField(default=False),
        ),
    ]
