# Generated by Django 4.1.7 on 2023-12-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0008_monivetoodds_bet"),
    ]

    operations = [
        migrations.AddField(
            model_name="combination",
            name="combination",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="combination",
            name="list_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combination",
            name="vakio_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="winshare",
            name="combination",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="winshare",
            name="list_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="winshare",
            name="vakio_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="combination",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="winshare",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
