# Generated by Django 4.1.7 on 2023-12-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0009_combination_combination_combination_list_index_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="combination",
            constraint=models.UniqueConstraint(
                fields=("list_index", "combination", "vakio_id"),
                name="unique_combination_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="winshare",
            constraint=models.UniqueConstraint(
                fields=("list_index", "combination", "vakio_id"),
                name="unique_winshare_id",
            ),
        ),
    ]
