# Generated by Django 4.1.7 on 2023-12-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0010_combination_unique_combination_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monivetoodds",
            name="combination",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetoodds",
            name="list_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetoodds",
            name="moniveto_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetoprob",
            name="combination",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetoprob",
            name="list_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetoprob",
            name="moniveto_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="monivetoodds",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="monivetoprob",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="monivetoodds",
            constraint=models.UniqueConstraint(
                fields=("list_index", "combination", "moniveto_id"),
                name="unique_moniveto_odds_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="monivetoprob",
            constraint=models.UniqueConstraint(
                fields=("list_index", "combination", "moniveto_id"),
                name="unique_moniveto_winshare_id",
            ),
        ),
    ]
