# Generated by Django 4.1.7 on 2023-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0011_monivetoodds_combination_monivetoodds_list_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonivetoBet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("combination_id", models.IntegerField()),
                ("bet", models.BooleanField(default=False)),
            ],
        ),
    ]
