# Generated by Django 4.1.7 on 2023-12-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0012_monivetobet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monivetobet",
            name="combination_id",
        ),
        migrations.AddField(
            model_name="monivetobet",
            name="combination",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetobet",
            name="list_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monivetobet",
            name="moniveto_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
