# Generated by Django 4.1.7 on 2024-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0013_remove_monivetobet_combination_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combination",
            name="value",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="monivetobet",
            name="value",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
