# Generated by Django 4.1.7 on 2024-01-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0014_combination_value_monivetobet_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="monivetobet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
