# Generated by Django 4.1.7 on 2024-02-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0015_monivetobet_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moniveto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moniveto_id", models.IntegerField()),
                ("list_index", models.IntegerField()),
                ("close", models.DateTimeField(auto_now_add=True, null=True)),
                ("stake", models.FloatField()),
                ("home1", models.TextField()),
                ("away1", models.TextField()),
                ("home2", models.TextField()),
                ("away2", models.TextField()),
                ("home3", models.TextField()),
                ("away3", models.TextField()),
                ("home4", models.TextField()),
                ("away4", models.TextField()),
            ],
        ),
    ]
