# Generated by Django 4.1.7 on 2024-02-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0016_moniveto"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="moniveto",
            constraint=models.UniqueConstraint(
                fields=("list_index", "moniveto_id"), name="unique_moniveto_id"
            ),
        ),
    ]
