# Generated by Django 4.1.7 on 2024-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vakio", "0017_moniveto_unique_moniveto_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="moniveto",
            name="scores",
            field=models.JSONField(default=None, null=True),
        ),
    ]
