# Generated by Django 4.1.7 on 2023-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("slug", models.TextField()),
            ],
        ),
    ]
