# Generated by Django 4.1.7 on 2023-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sportscore_id", models.IntegerField(null=True)),
                ("player_id", models.IntegerField(null=True)),
                ("dob", models.DateField(null=True)),
                ("hand", models.TextField(null=True)),
                ("country_code", models.TextField(null=True)),
                ("height", models.FloatField(null=True)),
                ("wikidata_id", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("section_id", models.IntegerField(null=True)),
                ("section_slug", models.TextField(null=True)),
                ("section_name", models.TextField(null=True)),
                ("priority", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("slug", models.TextField()),
                ("continent", models.TextField(null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("ground_type", models.TextField(null=True)),
                ("number_of_competitors", models.IntegerField(null=True)),
                ("number_of_sets", models.IntegerField(null=True)),
                ("prize_currency", models.TextField(null=True)),
                ("total_prize_money", models.IntegerField(null=True)),
            ],
        ),
    ]
