# Generated by Django 4.1.7 on 2023-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournaments",
            name="continent",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="ground_type",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="number_of_competitors",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="number_of_sets",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="prize_currency",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="start_date_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tournaments",
            name="total_prize_money",
            field=models.IntegerField(null=True),
        ),
    ]
