# Generated by Django 4.1.7 on 2023-03-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
