# Generated by Django 4.1.7 on 2023-03-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0002_alter_players_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="first_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="last_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="slug",
            field=models.TextField(null=True),
        ),
    ]
