# Generated by Django 4.1.7 on 2023-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0003_players_first_name_players_last_name_players_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpTour",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("surface", models.TextField(null=True)),
            ],
        ),
    ]
