# Generated by Django 4.1.7 on 2023-04-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0004_atptour"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="country",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="prize_total_euros",
            field=models.IntegerField(null=True),
        ),
    ]
