# Generated by Django 4.1.7 on 2023-04-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0005_players_country_players_prize_total_euros"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpMatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="losers",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="atptours",
                        to="tennisapi.atptour",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="winners",
                        to="tennisapi.players",
                    ),
                ),
            ],
        ),
    ]
