# Generated by Django 4.1.7 on 2023-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0006_atpmatches"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="round_name",
            field=models.TextField(null=True),
        ),
    ]
