# Generated by Django 4.1.7 on 2023-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0007_atpmatches_round_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="match_num",
            field=models.IntegerField(null=True),
        ),
    ]
