# Generated by Django 4.1.7 on 2023-04-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0008_atpmatches_match_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpElo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="match",
                        to="tennisapi.atpmatches",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="player",
                        to="tennisapi.players",
                    ),
                ),
            ],
        ),
    ]
