# Generated by Django 4.1.7 on 2023-04-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0009_atpelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                ("home_odds", models.TextField(null=True)),
                ("away_odds", models.TextField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matches",
                        to="tennisapi.atptour",
                    ),
                ),
            ],
        ),
    ]
