# Generated by Django 4.1.7 on 2023-04-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0010_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="date",
        ),
        migrations.AddField(
            model_name="match",
            name="start_at",
            field=models.DateTimeField(null=True),
        ),
    ]
