# Generated by Django 4.1.7 on 2023-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0011_remove_match_date_match_start_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WTAPlayers",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("sportscore_id", models.IntegerField(null=True)),
                ("player_id", models.IntegerField(null=True)),
                ("dob", models.DateField(null=True)),
                ("hand", models.TextField(null=True)),
                ("country_code", models.TextField(null=True)),
                ("height", models.FloatField(null=True)),
                ("wikidata_id", models.TextField(null=True)),
                ("first_name", models.TextField(null=True)),
                ("last_name", models.TextField(null=True)),
                ("slug", models.TextField(null=True)),
                ("country", models.TextField(null=True)),
                ("prize_total_euros", models.IntegerField(null=True)),
            ],
        ),
    ]
