# Generated by Django 4.1.7 on 2023-05-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0012_wtaplayers"),
    ]

    operations = [
        migrations.CreateModel(
            name="WtaTour",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("surface", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WtaMatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="losers",
                        to="tennisapi.wtaplayers",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="atptours",
                        to="tennisapi.wtatour",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="winners",
                        to="tennisapi.wtaplayers",
                    ),
                ),
            ],
        ),
    ]
