# Generated by Django 4.1.7 on 2023-05-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0013_wtatour_wtamatches"),
    ]

    operations = [
        migrations.CreateModel(
            name="WtaElo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wtamatch",
                        to="tennisapi.wtamatches",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wtaplayer",
                        to="tennisapi.wtaplayers",
                    ),
                ),
            ],
        ),
    ]
