# Generated by Django 4.1.7 on 2023-05-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0014_wtaelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WtaMatch",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                ("home_odds", models.TextField(null=True)),
                ("away_odds", models.TextField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="away",
                        to="tennisapi.wtaplayers",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="home",
                        to="tennisapi.wtaplayers",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wtamatches",
                        to="tennisapi.wtatour",
                    ),
                ),
            ],
        ),
    ]
