# Generated by Django 4.1.7 on 2023-05-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0016_chmatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChTour",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("surface", models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="chmatch",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="matches",
                to="tennisapi.chtour",
            ),
        ),
    ]
