# Generated by Django 4.1.7 on 2023-05-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0017_chtour_alter_chmatch_tour"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChMatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="chlosers",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="chtours",
                        to="tennisapi.chtour",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="chwinners",
                        to="tennisapi.players",
                    ),
                ),
            ],
        ),
    ]
