# Generated by Django 4.1.7 on 2023-05-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0019_chelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WtaHardElo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wtahardmatch",
                        to="tennisapi.wtamatches",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wtahardplayer",
                        to="tennisapi.wtaplayers",
                    ),
                ),
            ],
        ),
    ]
