# Generated by Django 4.1.7 on 2023-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0021_atphardelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpelo",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
