# Generated by Django 4.1.7 on 2023-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0022_atpelo_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="atphardelo",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
