# Generated by Django 4.1.7 on 2023-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0023_atphardelo_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="chelo",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="wtaelo",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="wtahardelo",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
