# Generated by Django 4.1.7 on 2023-05-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0024_chelo_date_wtaelo_date_wtahardelo_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="chmatch",
            name="winner_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="winner_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="winner_code",
            field=models.IntegerField(null=True),
        ),
    ]
