# Generated by Django 4.1.7 on 2023-06-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0026_wtamatchrolandg"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRolandG",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tour_id", models.TextField()),
                ("start_at", models.DateTimeField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                ("home_odds", models.TextField(null=True)),
                ("away_odds", models.TextField(null=True)),
                ("winner_code", models.IntegerField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="awayrg",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="homerg",
                        to="tennisapi.players",
                    ),
                ),
            ],
        ),
    ]
