# Generated by Django 4.1.7 on 2023-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0027_matchrolandg"),
    ]

    operations = [
        migrations.AddField(
            model_name="wtamatch",
            name="court_time",
            field=models.IntegerField(null=True),
        ),
    ]
