# Generated by Django 4.1.7 on 2023-06-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0028_wtamatch_court_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="court_time",
            field=models.IntegerField(null=True),
        ),
    ]
