# Generated by Django 4.1.7 on 2023-06-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0029_match_court_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="minutes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_1stin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_1stwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_2ndwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_ace",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_bpfaced",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_bpsaved",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_df",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_svgms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="w_svpt",
            field=models.IntegerField(null=True),
        ),
    ]
