# Generated by Django 4.1.7 on 2023-06-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0030_atpmatches_minutes_atpmatches_w_1stin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atpmatches",
            name="minutes",
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="court_time",
            field=models.IntegerField(null=True),
        ),
    ]
