# Generated by Django 4.1.7 on 2023-06-03 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0031_remove_atpmatches_minutes_atpmatches_court_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_1stin",
            new_name="w_firstin",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_1stwon",
            new_name="w_firstwon",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_2ndwon",
            new_name="w_secondwon",
        ),
    ]
