# Generated by Django 4.1.7 on 2023-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0032_rename_w_1stin_atpmatches_w_firstin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="l_ace",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_bpfaced",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_bpsaved",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_df",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_firstin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_firstwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_secondwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_svgms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="l_svpt",
            field=models.IntegerField(null=True),
        ),
    ]
