# Generated by Django 4.1.7 on 2023-06-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0033_atpmatches_l_ace_atpmatches_l_bpfaced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wtamatches",
            name="court_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_ace",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_bpfaced",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_bpsaved",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_df",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_firstin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_firstwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_secondwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_svgms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="l_svpt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_ace",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_bpfaced",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_bpsaved",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_df",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_firstin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_firstwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_secondwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_svgms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="w_svpt",
            field=models.IntegerField(null=True),
        ),
    ]
