# Generated by Django 4.1.7 on 2023-06-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0034_wtamatches_court_time_wtamatches_l_ace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpGrassElo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo", models.IntegerField()),
                ("elo_change", models.IntegerField()),
                ("games", models.IntegerField()),
                ("date", models.DateField(null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="grassmatch",
                        to="tennisapi.atpmatches",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="grassplayer",
                        to="tennisapi.players",
                    ),
                ),
            ],
        ),
    ]
