# Generated by Django 4.1.7 on 2023-07-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0036_wtagrasselo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpTourTest",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("surface", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchTest",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField(null=True)),
                ("round_name", models.TextField(null=True)),
                ("match_num", models.IntegerField(null=True)),
                ("home_odds", models.TextField(null=True)),
                ("away_odds", models.TextField(null=True)),
                ("winner_code", models.IntegerField(null=True)),
                ("court_time", models.IntegerField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="awaytest",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hometest",
                        to="tennisapi.players",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matchestest",
                        to="tennisapi.atptour",
                    ),
                ),
            ],
        ),
    ]
