# Generated by Django 4.1.7 on 2023-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0037_atptourtest_matchtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="event_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="event_id",
            field=models.TextField(null=True),
        ),
    ]
