# Generated by Django 4.1.7 on 2023-08-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0038_atpmatches_event_id_wtamatches_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="winner_code",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="winner_code",
            field=models.TextField(null=True),
        ),
    ]
