# Generated by Django 4.1.7 on 2024-01-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0040_bet"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetWta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_name", models.TextField(null=True)),
                ("away_name", models.TextField(null=True)),
                ("home_odds", models.FloatField(null=True)),
                ("away_odds", models.FloatField(null=True)),
                ("elo_prob", models.FloatField(null=True)),
                ("year_elo_prob", models.FloatField(null=True)),
                ("home_spw", models.FloatField(null=True)),
                ("home_rpw", models.FloatField(null=True)),
                ("away_spw", models.FloatField(null=True)),
                ("away_rpw", models.FloatField(null=True)),
                ("stats_win", models.FloatField(null=True)),
                ("home_fatigue", models.FloatField(null=True)),
                ("away_fatigue", models.FloatField(null=True)),
                ("h2h_win", models.FloatField(null=True)),
                ("h2h_matches", models.IntegerField(null=True)),
                ("walkover", models.BooleanField(null=True)),
                ("home_inj_score", models.FloatField(null=True)),
                ("away_inj_score", models.FloatField(null=True)),
                ("common_opponents", models.FloatField(null=True)),
                ("common_opponents_count", models.IntegerField(null=True)),
                ("preview", models.TextField(null=True)),
                ("reasoning", models.TextField(null=True)),
                ("start_at", models.DateTimeField(null=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="awaybet",
                        to="tennisapi.wtaplayers",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="homebet",
                        to="tennisapi.wtaplayers",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tennisapi.wtamatch",
                    ),
                ),
            ],
        ),
    ]
