# Generated by Django 4.1.7 on 2024-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0042_rename_walkover_bet_walkover_away_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_prob",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_yield",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_prob",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_yield",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_prob",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_yield",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_prob",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_yield",
            field=models.FloatField(null=True),
        ),
    ]
