# Generated by Django 4.1.7 on 2024-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0043_bet_away_prob_bet_away_yield_bet_home_prob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="away_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="home_score",
            field=models.IntegerField(null=True),
        ),
    ]
