# Generated by Django 4.1.7 on 2024-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0045_delete_atptourtest_remove_matchrolandg_away_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atpmatches",
            name="tour",
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="surface",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="tour_id",
            field=models.TextField(null=True),
        ),
    ]
