# Generated by Django 4.1.7 on 2024-03-10 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0046_remove_atpmatches_tour_atpmatches_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atpmatches",
            old_name="name",
            new_name="tourney_name",
        ),
    ]
