# Generated by Django 4.1.7 on 2024-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0047_rename_name_atpmatches_tourney_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wtamatches",
            name="tour",
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="surface",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="tour_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="tourney_name",
            field=models.TextField(null=True),
        ),
    ]
