# Generated by Django 4.1.7 on 2024-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0048_remove_wtamatches_tour_wtamatches_surface_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="tour",
        ),
        migrations.RemoveField(
            model_name="wtamatch",
            name="tour",
        ),
        migrations.AddField(
            model_name="match",
            name="tour_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="tour_id",
            field=models.TextField(null=True),
        ),
    ]
