# Generated by Django 4.1.7 on 2024-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tennisapi",
            "0049_remove_match_tour_remove_wtamatch_tour_match_tour_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="surface",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="surface",
            field=models.TextField(null=True),
        ),
    ]
