# Generated by Django 4.1.7 on 2024-03-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0050_bet_surface_betwta_surface"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="surface",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="surface",
            field=models.TextField(null=True),
        ),
    ]
