# Generated by Django 4.1.7 on 2024-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0051_match_surface_wtamatch_surface"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="tourney_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="tourney_name",
            field=models.TextField(null=True),
        ),
    ]
