# Generated by Django 4.1.7 on 2024-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0052_match_tourney_name_wtamatch_tourney_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="atp_name_full",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="name_full",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtaplayers",
            name="atp_name_full",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtaplayers",
            name="name_full",
            field=models.TextField(null=True),
        ),
    ]
