# Generated by Django 4.1.7 on 2024-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0053_players_atp_name_full_players_name_full_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_dr",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="current_rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_dr",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="matches",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="peak_rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="plays",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_dr",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="current_rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_dr",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="matches",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="peak_rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="plays",
            field=models.TextField(null=True),
        ),
    ]
