# Generated by Django 4.1.7 on 2024-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0055_remove_bet_current_rank_remove_bet_matches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_md_table",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_player_info",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_md_table",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_player_info",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_md_table",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_player_info",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_md_table",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_player_info",
            field=models.TextField(null=True),
        ),
    ]
