# Generated by Django 4.1.7 on 2024-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0056_bet_away_md_table_bet_away_player_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_short_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_short_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_short_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_preview",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_short_preview",
            field=models.TextField(null=True),
        ),
    ]
