# Generated by Django 4.1.7 on 2024-03-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0057_bet_away_preview_bet_away_short_preview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="away_peak_rank",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="bet",
            name="home_peak_rank",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="betwta",
            name="away_peak_rank",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="betwta",
            name="home_peak_rank",
            field=models.TextField(null=True),
        ),
    ]
