# Generated by Django 4.1.7 on 2024-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0059_bet_away_ah_2_5_bet_away_ah_3_5_bet_away_ah_4_5_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_win_1_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_win_2_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_win_single_game",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_win_single_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_wins_1_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_wins_2_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_wins_single_game",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_wins_single_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_win_1_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_win_2_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_win_single_game",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_win_single_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_wins_1_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_wins_2_set",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_wins_single_game",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_wins_single_set",
            field=models.FloatField(null=True),
        ),
    ]
