# Generated by Django 4.1.7 on 2024-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0060_bet_away_win_1_set_bet_away_win_2_set_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_ah_7_5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_ah_7_5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="away_ah_7_5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="home_ah_7_5",
            field=models.FloatField(null=True),
        ),
    ]
