# Generated by Django 4.1.7 on 2024-06-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0062_bet_away_dr_clay_bet_away_matches_clay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="away_dr_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_matches_grass",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_rpw_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="away_spw_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="elo_prob_clay",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="elo_prob_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_dr_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_matches_grass",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_rpw_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="home_spw_grass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="bet",
            name="stats_win_grass",
            field=models.FloatField(null=True),
        ),
    ]
