# Generated by Django 4.1.7 on 2024-08-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0064_betwta_away_dr_grass_betwta_away_matches_grass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="away_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="home_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="away_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatch",
            name="home_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="away_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="home_name",
            field=models.TextField(null=True),
        ),
    ]
