# Generated by Django 4.1.7 on 2024-08-02 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0065_atpmatches_away_name_atpmatches_home_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atpmatches",
            old_name="away_name",
            new_name="loser_name",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="home_name",
            new_name="winner_name",
        ),
        migrations.RenameField(
            model_name="wtamatches",
            old_name="away_name",
            new_name="loser_name",
        ),
        migrations.RenameField(
            model_name="wtamatches",
            old_name="home_name",
            new_name="winner_name",
        ),
    ]
