# Generated by Django 4.1.7 on 2024-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0066_rename_away_name_atpmatches_loser_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atpmatches",
            name="loser_receive_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="loser_service_points_total",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="loser_service_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="winner_receive_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="winner_service_points_total",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="atpmatches",
            name="winner_service_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="loser_receive_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="loser_service_points_total",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="loser_service_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="winner_receive_points_won",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="winner_service_points_total",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wtamatches",
            name="winner_service_points_won",
            field=models.IntegerField(null=True),
        ),
    ]
