# Generated by Django 4.1.7 on 2024-08-02 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tennisapi",
            "0068_rename_loser_receive_points_won_atpmatches_loser_receiver_points_won_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="atpmatches",
            old_name="loser_service_points_total",
            new_name="loser_total_points",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="winner_service_points_total",
            new_name="winner_total_points",
        ),
        migrations.RenameField(
            model_name="wtamatches",
            old_name="loser_service_points_total",
            new_name="loser_total_points",
        ),
        migrations.RenameField(
            model_name="wtamatches",
            old_name="winner_service_points_total",
            new_name="winner_total_points",
        ),
    ]
