# Generated by Django 4.1.7 on 2024-08-10 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tennisapi",
            "0069_rename_loser_service_points_total_atpmatches_loser_total_points_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AtpElo",
            new_name="AtpClayElo",
        ),
        migrations.RenameModel(
            old_name="ChElo",
            new_name="ChClayElo",
        ),
        migrations.RenameModel(
            old_name="WtaElo",
            new_name="WtaClayElo",
        ),
    ]
