# Generated by Django 4.1.7 on 2024-08-10 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0070_rename_atpelo_atpclayelo_rename_chelo_chclayelo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bet",
            old_name="elo_prob",
            new_name="elo_prob_hard",
        ),
        migrations.RenameField(
            model_name="betwta",
            old_name="elo_prob",
            new_name="elo_prob_hard",
        ),
    ]
