# Generated by Django 4.1.7 on 2024-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennisapi", "0071_rename_elo_prob_bet_elo_prob_hard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="stats_win_hard",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="betwta",
            name="stats_win_hard",
            field=models.FloatField(null=True),
        ),
    ]
