---
openapi: 3.1.0
info:
  version: '1.0'
  title: Tennis api
  description: >
    Api service to Tennis Dataengine.
tags:
  - name: players
    description: All players
    externalDocs:
      description: Find out more about the service
      url: https://tennis.com
  - name: elo
    description: Elo ratings
paths:
  /players:
    get:
      tags:
        - players
      summary: Get players
      operationId: getPlayers
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Players'
        '404':
          description: Players not found
  /atp-elo:
    get:
      tags:
        - players
      summary: Get elo ratings
      operationId: getEloRatings
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EloRatings'
        '404':
          description: EloRatings not found
  /bet-list:
    get:
      tags:
        - bets
      summary: Get bets
      operationId: getBets
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bets'
        '404':
          description: Bet list not found
  /football-bet-list:
    get:
      tags:
        - bets
      summary: Get football bets
      operationId: getFootballBets
      parameters:
        - $ref: '#/components/parameters/leagueParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FootballBets'
        '404':
          description: Bet list not found
servers:
  - url: /api/tennisapi
  - url: http://localhost:3000/api/metricsapi
components:
  parameters:
    levelParam:
      in: query
      name: level
      description: Players
      schema:
        type: string
        example: "WTA"
    leagueParam:
      in: query
      name: level
      description: Football league
      schema:
        type: string
        example: "bundesliga"
  schemas:
    Players:
      type: object
      properties:
        id:
          type: string
          example: 4b145708-4e99-4547-ad02-1f3332e7708d
          description: "Player ID"
        first_name:
          type: string
          description: "First name"
        last_name:
          type: string
          description: "last_name"
        dob:
          type: string
          description: "dob"
        hand:
          type: string
          description: "hand"
        height:
          type: string
          description: "height"
        slug:
          type: string
          description: "slug"
        prize_total_euros:
          type: string
          description: "prize_total_euros"
    EloRatings:
      type: object
      properties:
        id:
          type: string
          example: 4b145708-4e99-4547-ad02-1f3332e7708d
          description: "Player ID"
        first_name:
          type: string
          description: "First name"
        last_name:
          type: string
          description: "Last Name"
        elo:
          type: integer
          description: "EloRating"
        latest_date:
          type: integer
          description: "Latest Record Date"
    Bets:
      type: object
      properties:
        matchId:
          type: string
          example: 30a3c3d440e92221838639139110da3b
          description: "Match ID"
        homeId:
          type: string
          description: "Home Player ID"
        awayId:
          type: string
          description: "Away Player ID"
        homeName:
          type: string
          description: "Home Player Name"
        awayName:
          type: string
          description: "Away Player Name"
        homeOdds:
          type: number
          description: "Home Odds"
        awayOdds:
          type: number
          description: "Away Odds"
        homeProb:
          type: number
          description: "Home Probability"
        awayProb:
          type: number
          description: "Away Probability"
        homeYield:
          type: number
          description: "Home yield"
        awayYield:
          type: number
          description: "Away yield"
        eloProb:
          type: number
          description: "Elo Probability"
        yearEloProb:
          type: number
          description: "Current Year Elo Probability"
        homeSpw:
          type: number
          description: "Home Service Points Won"
        awaySpw:
          type: number
          description: "Away Service Points Won"
        homeRpw:
          type: number
          description: "Home Return Points Won"
        awayRpw:
          type: number
          description: "Away Return Points Won"
        statsWin:
          type: number
          description: "Calculate home win probability based on stats"
        homeFatigue:
          type: number
          description: "Fatigue score for home player"
        awayFatigue:
          type: number
          description: "Fatigue score for away player"
        h2hWin:
          type: number
          description: "Head to head win probability"
        h2hMatches:
          type: integer
          description: "Head to head matches"
        walkover:
          type: boolean
          description: "Last match was a retirement"
        homeInjScore:
          type: number
          description: "How long have not played"
        awayInjScore:
          type: number
          description: "How long have not played"
        commonOpponents:
          type: integer
          description: "Home winning percentage calculated from common opponents"
        commonOpponentsCount:
          type: integer
          description: "Count of common opponents"
        preview:
          type: string
          description: "Preview"
        reasoning:
          type: string
          description: "Reasoning"
        startAt:
          type: string
          format: date-time
          description: "Start time"
        homeStatMatches:
          type: integer
          description: "Home player matches"
        awayStatMatches:
          type: integer
          description: "Away player matches"
    FootballBets:
      type: object
      properties:
        matchId:
          type: string
          example: 30a3c3d440e92221838639139110da3b
          description: "Match ID"
        homeId:
          type: string
          description: "Home Team ID"
        awayId:
          type: string
          description: "Away Team ID"
        homeName:
          type: string
          description: "Home Team Name"
        awayName:
          type: string
          description: "Away Team Name"
        homeOdds:
          type: number
          description: "Home Odds"
        drawOdds:
          type: number
          description: "Draw Odds"
        awayOdds:
          type: number
          description: "Away Odds"
        homeProb:
          type: number
          description: "Home Probability"
        drawProb:
          type: number
          description: "Draw Probability"
        awayProb:
          type: number
          description: "Away Probability"
        homeYield:
          type: number
          description: "Home yield"
        drawYield:
          type: number
          description: "Draw yield"
        awayYield:
          type: number
          description: "Away yield"
        eloProb:
          type: number
          description: "Elo Probability"
        eloProbHome:
          type: number
          description: "Home and Away Elo Probability"
        preview:
          type: string
          description: "Preview"
        reasoning:
          type: string
          description: "Reasoning"
        startAt:
          type: string
          format: date-time
          description: "Start time"

x-json-schema-faker:
  min-items: 2
  max-items: 10
