---
openapi: 3.1.0
info:
  version: '1.0'
  title: Tennis api
  description: >
    Api service to Tennis Dataengine.
tags:
  - name: players
    description: All players
    externalDocs:
      description: Find out more about the service
      url: https://tennis.com
  - name: elo
    description: Elo ratings
paths:
  /players:
    get:
      tags:
        - players
      summary: Get players
      operationId: getPlayers
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Players'
        '404':
          description: Players not found
  /atp-elo:
    get:
      tags:
        - players
      summary: Get elo ratings
      operationId: getEloRatings
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EloRatings'
        '404':
          description: EloRatings not found
  /bet-list:
    get:
      tags:
        - bets
      summary: Get bets
      operationId: getBets
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bets'
        '404':
          description: Bet list not found
  /player-statistics:
    get:
      tags:
        - statistics
      summary: Get player statistics
      operationId: getPlayerStatistics
      parameters:
        - $ref: '#/components/parameters/levelParam'
        - $ref: '#/components/parameters/playerIdParam'
        - $ref: '#/components/parameters/surfaceParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerStatistics'
        '404':
          description: Player statistics not found
  /match-probs:
    get:
      tags:
        - statistics
      summary: Get match probabilities
      operationId: getMatchProbabilities
      parameters:
        - $ref: '#/components/parameters/tourNameParam'
        - $ref: '#/components/parameters/homeSPWParam'
        - $ref: '#/components/parameters/surfaceParam'
        - $ref: '#/components/parameters/homeRPWParam'
        - $ref: '#/components/parameters/awayRPWParam'
        - $ref: '#/components/parameters/awaySPWParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchProbabilities'
        '404':
          description: Match probabilities not found
  /football-bet-list:
    get:
      tags:
        - bets
      summary: Get football bets
      operationId: getFootballBets
      parameters:
        - $ref: '#/components/parameters/leagueParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FootballBets'
        '404':
          description: Bet list not found
servers:
  - url: /api/tennisapi
  - url: http://localhost:3000/api/metricsapi
components:
  parameters:
    levelParam:
      in: query
      name: level
      description: League level
      schema:
        type: string
        example: "WTA"
    playerIdParam:
        in: query
        name: playerId
        description: Player ID
        schema:
            type: string
            example: "4b145708-4e99-4547-ad02-1f3332e7708d"
    surfaceParam:
        in: query
        name: surface
        description: Surface
        schema:
            type: string
            example: "clay"
    tourNameParam:
        in: query
        name: tourName
        description: Tournament Name
        schema:
            type: string
            example: "Wimbledon"
    homeSPWParam:
        in: query
        name: homeSPW
        description: Home Service Points Won
        schema:
            type: number
            example: 0.6
    homeRPWParam:
        in: query
        name: homeRPW
        description: Home Return Points Won
        schema:
            type: number
            example: 0.4
    awaySPWParam:
        in: query
        name: awaySPW
        description: Away Service Points Won
        schema:
            type: number
            example: 0.6
    awayRPWParam:
        in: query
        name: awayRPW
        description: Away Return Points Won
        schema:
            type: number
            example: 0.4
    leagueParam:
      in: query
      name: level
      description: Football league
      schema:
        type: string
        example: "bundesliga"
  schemas:
    Players:
      type: object
      properties:
        id:
          type: string
          example: 4b145708-4e99-4547-ad02-1f3332e7708d
          description: "Player ID"
        first_name:
          type: string
          description: "First name"
        last_name:
          type: string
          description: "last_name"
        dob:
          type: string
          description: "dob"
        hand:
          type: string
          description: "hand"
        height:
          type: string
          description: "height"
        slug:
          type: string
          description: "slug"
        prize_total_euros:
          type: string
          description: "prize_total_euros"
    EloRatings:
      type: object
      properties:
        id:
          type: string
          example: 4b145708-4e99-4547-ad02-1f3332e7708d
          description: "Player ID"
        first_name:
          type: string
          description: "First name"
        last_name:
          type: string
          description: "Last Name"
        elo:
          type: integer
          description: "EloRating"
        latest_date:
          type: integer
          description: "Latest Record Date"
    MatchProbabilities:
      type: object
      properties:
        eventSPW:
          type: number
          example: 0.6
          description: "Event Average Service Points Won"
        eventRPW:
          type: number
          example: 0.4
          description: "Event Average Return Points Won"
        matchProb:
          type: number
          example: 0.6
          description: "Match Probability"
    PlayerStatistics:
      type: object
      properties:
        playerSPW:
          type: number
          example: 0.6
          description: "Service Points Won"
        playerRPW:
            type: number
            example: 0.4
            description: "Return Points Won"
        playerMatches:
            type: number
            example: 10
            description: "Matches Played"
        matches:
          type: object
          properties:
            date:
              type: array
              items:
                type: string
                format: date
                description: Date of the match
            surface:
              type: array
              items:
                type: string
                description: Surface type of the match
            round_name:
              type: array
              items:
                type: string
                description: Round name of the match
            tourney_name:
              type: array
              items:
                type: string
                description: Tournament name of the match
            spw:
              type: array
              items:
                type: number
                format: float
                description: Serve points won in the match
            rpw:
              type: array
              items:
                type: number
                format: float
                description: Return points won in the match
    Bets:
      type: object
      properties:
        matchId:
          type: string
          example: 30a3c3d440e92221838639139110da3b
          description: "Match ID"
        homeId:
          type: string
          description: "Home Player ID"
        awayId:
          type: string
          description: "Away Player ID"
        homeName:
          type: string
          description: "Home Player Name"
        awayName:
          type: string
          description: "Away Player Name"
        homeOdds:
          type: number
          description: "Home Odds"
        awayOdds:
          type: number
          description: "Away Odds"
        homeProb:
          type: number
          description: "Home Probability"
        awayProb:
          type: number
          description: "Away Probability"
        homeYield:
          type: number
          description: "Home yield"
        awayYield:
          type: number
          description: "Away yield"
        eloProbHard:
          type: number
          description: "Elo Probability"
        eloProbClay:
          type: number
          description: "Elo Probability on Clay"
        eloProbGrass:
          type: number
          description: "Elo Probability on Grass"
        yearEloProb:
          type: number
          description: "Current Year Elo Probability"
        homeSpw:
          type: number
          description: "Home Service Points Won"
        awaySpw:
          type: number
          description: "Away Service Points Won"
        homeRpw:
          type: number
          description: "Home Return Points Won"
        awayRpw:
          type: number
          description: "Away Return Points Won"
        statsWin:
          type: number
          description: "Calculate home win probability based on stats"
        statsWinHard:
          type: number
          description: "Calculate home win probability based on stats on hard"
        homeFatigue:
          type: number
          description: "Fatigue score for home player"
        awayFatigue:
          type: number
          description: "Fatigue score for away player"
        h2hWin:
          type: number
          description: "Head to head win probability"
        h2hMatches:
          type: integer
          description: "Head to head matches"
        walkover:
          type: boolean
          description: "Last match was a retirement"
        homeInjScore:
          type: number
          description: "How long have not played"
        awayInjScore:
          type: number
          description: "How long have not played"
        commonOpponents:
          type: integer
          description: "Home winning percentage calculated from common opponents"
        commonOpponentsCount:
          type: integer
          description: "Count of common opponents"
        preview:
          type: string
          description: "Preview"
        reasoning:
          type: string
          description: "Reasoning"
        startAt:
          type: string
          format: date-time
          description: "Start time"
        homeStatMatches:
          type: integer
          description: "Home player matches"
        awayStatMatches:
          type: integer
          description: "Away player matches"
        homeMatches:
          type: string
          description: "Home player matches"
        awayMatches:
            type: string
            description: "Away player matches"
        homePlays:
          type: string
          description: "Home player plays"
        awayPlays:
          type: string
          description: "Away player plays"
        homeCurrentRank:
          type: integer
          description: "Home player current rank"
        awayCurrentRank:
            type: integer
            description: "Away player current rank"
        homePeakRank:
          type: integer
          description: "Home player peak rank"
        awayPeakRank:
          type: integer
          description: "Away player peak rank"
        homeDr:
          type: number
          description: "Home player dominance ratio"
        awayDr:
          type: number
          description: "Away player dominance ratio"
        homePreview:
          type: string
          description: "Home team preview"
        awayPreview:
          type: string
          description: "Away team preview"
        homeShortPreview:
          type: string
          description: "Home team short preview"
        awayShortPreview:
          type: string
          description: "Away team short preview"
        homeTable:
          type: string
          description: "Home team table"
        awayTable:
          type: string
          description: "Away team table"
        homePlayerInfo:
          type: string
          description: "Home player info"
        awayPlayerInfo:
          type: string
          description: "Away player info"
        homeAH7_5:
          type: number
          description: "Home player AH7.5"
        homeAH6_5:
          type: number
          description: "Home player AH6.5"
        homeAH5_5:
          type: number
          description: "Home player AH5.5"
        homeAH4_5:
          type: number
          description: "Home player AH4.5"
        homeAH3_5:
          type: number
          description: "Home player AH3.5"
        homeAH2_5:
          type: number
          description: "Home player AH2.5"
        awayAH7_5:
          type: number
          description: "away player AH7.5"
        awayAH6_5:
          type: number
          description: "away player AH6.5"
        awayAH5_5:
          type: number
          description: "away player AH5.5"
        awayAH4_5:
          type: number
          description: "away player AH4.5"
        awayAH3_5:
          type: number
          description: "away player AH3.5"
        awayAH2_5:
          type: number
          description: "away player AH2.5"
        gamesOver21_5:
          type: number
          description: "Games over 21.5"
        gamesOver22_5:
          type: number
          description: "Games over 22.5"
        gamesOver23_5:
          type: number
          description: "Games over 23.5"
        gamesOver24_5:
          type: number
          description: "Games over 24.5"
        gamesOver25_5:
          type: number
          description: "Games over 25.5"
        homeWinSingleGame:
          type: number
          description: "Home player win single games"
        awayWinSingleGame:
          type: number
          description: "Away player win single games"
        homeWinSingleSet:
          type: number
          description: "Home player win single sets"
        awayWinSingleSet:
          type: number
          description: "Away player win single sets"
        homeWin1Set:
          type: number
          description: "Home player win 1 set"
        awayWin1Set:
          type: number
          description: "Away player win 1 set"
        homeWin2Set:
          type: number
          description: "Home player win 2 sets"
        awayWin2Set:
          type: number
          description: "Away player win 2 sets"
        homeSpwClay:
          type: number
          description: "Home player spw on clay"
        awaySpwClay:
          type: number
          description: "Away player spw on clay"
        homeRpwClay:
          type: number
          description: "Home player rpw on clay"
        awayRpwClay:
          type: number
          description: "Away player rpw on clay"
        homeSpwGrass:
          type: number
          description: "Home player spw on grass"
        awaySpwGrass:
          type: number
          description: "Away player spw on grass"
        homeRpwGrass:
          type: number
          description: "Home player rpw on grass"
        awayRpwGrass:
          type: number
          description: "Away player rpw on grass"
        statsWinClay:
          type: number
          description: "Stats win on clay"
        statsWinGrass:
          type: number
          description: "Stats win on grass"
        homeMatchesClay:
          type: string
          description: "Home player matches on clay"
        awayMatchesClay:
          type: string
          description: "Away player matches on clay"
        homeMatchesGrass:
          type: string
          description: "Home player matches on grass"
        awayMatchesGrass:
            type: string
            description: "Away player matches on grass"
        surface:
          type: string
          description: "clay"
    FootballBets:
      type: object
      properties:
        matchId:
          type: string
          example: 30a3c3d440e92221838639139110da3b
          description: "Match ID"
        homeId:
          type: string
          description: "Home Team ID"
        awayId:
          type: string
          description: "Away Team ID"
        homeName:
          type: string
          description: "Home Team Name"
        awayName:
          type: string
          description: "Away Team Name"
        homeOdds:
          type: number
          description: "Home Odds"
        drawOdds:
          type: number
          description: "Draw Odds"
        awayOdds:
          type: number
          description: "Away Odds"
        homeProb:
          type: number
          description: "Home Probability"
        drawProb:
          type: number
          description: "Draw Probability"
        awayProb:
          type: number
          description: "Away Probability"
        homeYield:
          type: number
          description: "Home yield"
        drawYield:
          type: number
          description: "Draw yield"
        awayYield:
          type: number
          description: "Away yield"
        eloProb:
          type: number
          description: "Elo Probability"
        eloProbHome:
          type: number
          description: "Home and Away Elo Probability"
        preview:
          type: string
          description: "Preview"
        reasoning:
          type: string
          description: "Reasoning"
        startAt:
          type: string
          format: date-time
          description: "Start time"

x-json-schema-faker:
  min-items: 2
  max-items: 10
