---
openapi: 3.1.0
info:
  version: '1.0'
  title: Tennis api
  description: >
    Api service to Tennis Dataengine.
tags:
  - name: players
    description: All players
    externalDocs:
      description: Find out more about the service
      url: https://tennis.com
  - name: elo
    description: Elo ratings
paths:
  /players:
    get:
      tags:
        - players
      summary: Get players
      operationId: getPlayers
      parameters:
        - $ref: '#/components/parameters/levelParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Players'
        '404':
          description: Players not found
servers:
  - url: /api/tennisapi
  - url: http://localhost:3000/api/metricsapi
components:
  parameters:
    levelParam:
      in: query
      name: level
      description: Players
      schema:
        type: string
        example: "WTA"
  schemas:
    Players:
      type: object
      properties:
        id:
          type: string
          example: 4b145708-4e99-4547-ad02-1f3332e7708d
          description: "Player ID"
        first_name:
          type: string
          description: "First name"
        last_name:
          type: string
          description: "last_name"
        dob:
          type: string
          description: "dob"
        hand:
          type: string
          description: "hand"
        height:
          type: string
          description: "height"
        slug:
          type: string
          description: "slug"
        prize_total_euros:
          type: string
          description: "prize_total_euros"
x-json-schema-faker:
  min-items: 2
  max-items: 10
