from django.db import models


class Players(models.Model):
    player_id = models.TextField(primary_key=True)
    name_first = models.TextField(null=True)
    name_last = models.TextField(null=True)
    hand = models.TextField(null=True)
    dob = models.TextField(null=True)
    ioc = models.TextField(null=True)
    height = models.TextField(null=True)
    wikidata_id = models.TextField(null=True)


class WTAPlayers(models.Model):
    player_id = models.TextField(primary_key=True)
    name_first = models.TextField(null=True)
    name_last = models.TextField(null=True)
    hand = models.TextField(null=True)
    dob = models.TextField(null=True)
    ioc = models.TextField(null=True)
    height = models.TextField(null=True)
    wikidata_id = models.TextField(null=True)


class AtpMatches(models.Model):
    id = models.AutoField(primary_key=True)
    tourney_id = models.TextField()
    tourney_name = models.TextField(null=True)
    surface = models.TextField(null=True)
    draw_size = models.TextField(null=True)
    tourney_level = models.TextField(null=True)
    tourney_date = models.TextField(null=True)
    match_num = models.TextField(null=True)
    winner_id = models.TextField(null=True)
    winner_seed = models.TextField(null=True)
    winner_entry = models.TextField(null=True)
    winner_name = models.TextField(null=True)
    winner_hand = models.TextField(null=True)
    winner_ht = models.TextField(null=True)
    winner_ioc = models.TextField(null=True)
    winner_age = models.TextField(null=True)
    loser_id = models.TextField(null=True)
    loser_seed = models.TextField(null=True)
    loser_entry = models.TextField(null=True)
    loser_name = models.TextField(null=True)
    loser_hand = models.TextField(null=True)
    loser_ht = models.TextField(null=True)
    loser_ioc = models.TextField(null=True)
    loser_age = models.TextField(null=True)
    score = models.TextField(null=True)
    best_of = models.TextField(null=True)
    round = models.TextField(null=True)
    minutes = models.IntegerField(null=True)
    w_ace = models.IntegerField(null=True)
    w_df = models.IntegerField(null=True)
    w_svpt = models.IntegerField(null=True)
    w_firstin = models.IntegerField(null=True)
    w_firstwon = models.IntegerField(null=True)
    w_secondwon = models.IntegerField(null=True)
    w_svgms = models.IntegerField(null=True)
    w_bpsaved = models.IntegerField(null=True)
    w_bpfaced = models.IntegerField(null=True)
    l_ace = models.IntegerField(null=True)
    l_df = models.IntegerField(null=True)
    l_svpt = models.IntegerField(null=True)
    l_firstin = models.IntegerField(null=True)
    l_firstwon = models.IntegerField(null=True)
    l_secondwon = models.IntegerField(null=True)
    l_svgms = models.IntegerField(null=True)
    l_bpsaved = models.IntegerField(null=True)
    l_bpfaced = models.IntegerField(null=True)
    winner_rank = models.TextField(null=True)
    winner_rank_points = models.TextField(null=True)
    loser_rank = models.TextField(null=True)
    loser_rank_points = models.TextField(null=True)


class WtaMatches(models.Model):
    id = models.AutoField(primary_key=True)
    tourney_id = models.TextField()
    tourney_name = models.TextField(null=True)
    surface = models.TextField(null=True)
    draw_size = models.TextField(null=True)
    tourney_level = models.TextField(null=True)
    tourney_date = models.TextField(null=True)
    match_num = models.TextField(null=True)
    winner_id = models.TextField(null=True)
    winner_seed = models.TextField(null=True)
    winner_entry = models.TextField(null=True)
    winner_name = models.TextField(null=True)
    winner_hand = models.TextField(null=True)
    winner_ht = models.TextField(null=True)
    winner_ioc = models.TextField(null=True)
    winner_age = models.TextField(null=True)
    loser_id = models.TextField(null=True)
    loser_seed = models.TextField(null=True)
    loser_entry = models.TextField(null=True)
    loser_name = models.TextField(null=True)
    loser_hand = models.TextField(null=True)
    loser_ht = models.TextField(null=True)
    loser_ioc = models.TextField(null=True)
    loser_age = models.TextField(null=True)
    score = models.TextField(null=True)
    best_of = models.TextField(null=True)
    round = models.TextField(null=True)
    minutes = models.IntegerField(null=True)
    w_ace = models.IntegerField(null=True)
    w_df = models.IntegerField(null=True)
    w_svpt = models.IntegerField(null=True)
    w_firstin = models.IntegerField(null=True)
    w_firstwon = models.IntegerField(null=True)
    w_secondwon = models.IntegerField(null=True)
    w_svgms = models.IntegerField(null=True)
    w_bpsaved = models.IntegerField(null=True)
    w_bpfaced = models.IntegerField(null=True)
    l_ace = models.IntegerField(null=True)
    l_df = models.IntegerField(null=True)
    l_svpt = models.IntegerField(null=True)
    l_firstin = models.IntegerField(null=True)
    l_firstwon = models.IntegerField(null=True)
    l_secondwon = models.IntegerField(null=True)
    l_svgms = models.IntegerField(null=True)
    l_bpsaved = models.IntegerField(null=True)
    l_bpfaced = models.IntegerField(null=True)
    winner_rank = models.TextField(null=True)
    winner_rank_points = models.TextField(null=True)
    loser_rank = models.TextField(null=True)
    loser_rank_points = models.TextField(null=True)

