# Generated by Django 4.1.7 on 2024-03-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icehockeyapi", "0003_beticehockey"),
    ]

    operations = [
        migrations.AddField(
            model_name="beticehockey",
            name="away_est_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="beticehockey",
            name="away_poisson",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="beticehockey",
            name="draw_poisson",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="beticehockey",
            name="home_est_goals",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="beticehockey",
            name="home_poisson",
            field=models.FloatField(null=True),
        ),
    ]
