"""
Django settings for tennisproject project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import environ

env = environ.FileAwareEnv(
    # set casting, default value
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    USE_X_FORWARDED_HOST=(bool, False),
    TEST_OUTPUT_DIR=(str, "build/test"),
    DJANGO_LOG_LEVEL=(str, "INFO"),
    DJANGO_DB_LOG_LEVEL=(str, "INFO"),
    DJANGO_LOG_FORMATTER=(str, "json"),
    AZURE_LOG_LEVEL=(str, "WARNING"),
    DATALAB_VIEWS_LOG_LEVEL=(str, "INFO"),
    ZENDESK_INITIAL_SYNC_DAYS=(int, 180),
    IS_GUNICORN_WORKER=(bool, False),
    OPENAI_API_KEY=(str, None),
    SPORT_SCORE_KEY=(str, None),
    DATABASE_REPLICA_URL=(str, None),
    ENVIRONMENT=(str, "production"),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-bo3g0ho-d1mm371p^w%@*sir(imgzhe38^y_mndtqfepff&c89"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

USE_X_FORWARDED_HOST = env("USE_X_FORWARDED_HOST")

ENVIRONMENT = env("ENVIRONMENT")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "sportscore",
    "tennisapi",
    "tennis_atp",
    "corsheaders",
    "vakio",
    "footballapi",
    "icehockeyapi",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "tennisproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tennisproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tennis',
        'USER': 'tennis',
        'PASSWORD': 'tennis',
        'HOST': 'db',
        'PORT': 5432,
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

OPENAI_API_KEY = env("OPENAI_API_KEY")
SPORT_SCORE_KEY = env("SPORT_SCORE_KEY")


ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

