# Generated by Django 4.1.7 on 2023-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                ("player_id", models.TextField(primary_key=True, serialize=False)),
                ("name_first", models.TextField(null=True)),
                ("name_last", models.TextField(null=True)),
                ("hand", models.TextField(null=True)),
                ("dob", models.TextField(null=True)),
                ("ioc", models.TextField(null=True)),
                ("height", models.TextField(null=True)),
                ("wikidata_id", models.TextField(null=True)),
            ],
        ),
    ]
