# Generated by Django 4.1.7 on 2023-03-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_atp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtpMatches",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tourney_id", models.TextField()),
                ("tourney_name", models.TextField(null=True)),
                ("surface", models.TextField(null=True)),
                ("draw_size", models.TextField(null=True)),
                ("tourney_level", models.TextField(null=True)),
                ("tourney_date", models.TextField(null=True)),
                ("match_num", models.TextField(null=True)),
                ("winner_id", models.TextField(null=True)),
                ("winner_seed", models.TextField(null=True)),
                ("winner_entry", models.TextField(null=True)),
                ("winner_name", models.TextField(null=True)),
                ("winner_hand", models.TextField(null=True)),
                ("winner_ht", models.TextField(null=True)),
                ("winner_ioc", models.TextField(null=True)),
                ("winner_age", models.TextField(null=True)),
                ("loser_id", models.TextField(null=True)),
                ("loser_seed", models.TextField(null=True)),
                ("loser_entry", models.TextField(null=True)),
                ("loser_name", models.TextField(null=True)),
                ("loser_hand", models.TextField(null=True)),
                ("loser_ht", models.TextField(null=True)),
                ("loser_ioc", models.TextField(null=True)),
                ("loser_age", models.TextField(null=True)),
                ("score", models.TextField(null=True)),
                ("best_of", models.TextField(null=True)),
                ("round", models.TextField(null=True)),
                ("minutes", models.TextField(null=True)),
                ("w_ace", models.TextField(null=True)),
                ("w_df", models.TextField(null=True)),
                ("w_svpt", models.TextField(null=True)),
                ("w_1stIn", models.TextField(null=True)),
                ("w_1stWon", models.TextField(null=True)),
                ("w_2ndWon", models.TextField(null=True)),
                ("w_SvGms", models.TextField(null=True)),
                ("w_bpSaved", models.TextField(null=True)),
                ("w_bpFaced", models.TextField(null=True)),
                ("l_ace", models.TextField(null=True)),
                ("l_df", models.TextField(null=True)),
                ("l_svpt", models.TextField(null=True)),
                ("l_1stIn", models.TextField(null=True)),
                ("l_1stWon", models.TextField(null=True)),
                ("l_2ndWon", models.TextField(null=True)),
                ("l_SvGms", models.TextField(null=True)),
                ("l_bpSaved", models.TextField(null=True)),
                ("l_bpFaced", models.TextField(null=True)),
                ("winner_rank", models.TextField(null=True)),
                ("winner_rank_points", models.TextField(null=True)),
                ("loser_rank", models.TextField(null=True)),
                ("loser_rank_points", models.TextField(null=True)),
            ],
        ),
    ]
