# Generated by Django 4.1.7 on 2023-03-28 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_atp", "0002_tournaments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tournaments",
            new_name="AtpMatches",
        ),
    ]
