# Generated by Django 4.1.7 on 2023-06-03 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_atp", "0004_wtamatches"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_1stIn",
            new_name="w_1stin",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_1stWon",
            new_name="w_1stwon",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_2ndWon",
            new_name="w_2ndwon",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_bpFaced",
            new_name="w_bpfaced",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_bpSaved",
            new_name="w_bpsaved",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="w_SvGms",
            new_name="w_svgms",
        ),
    ]
