# Generated by Django 4.1.7 on 2023-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_atp", "0005_rename_w_1stin_atpmatches_w_1stin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atpmatches",
            old_name="l_1stIn",
            new_name="l_1stin",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="l_1stWon",
            new_name="l_1stwon",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="l_2ndWon",
            new_name="l_2ndwon",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="l_bpFaced",
            new_name="l_bpfaced",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="l_bpSaved",
            new_name="l_bpsaved",
        ),
        migrations.RenameField(
            model_name="atpmatches",
            old_name="l_SvGms",
            new_name="l_svgms",
        ),
    ]
