# Generated by Django 4.1.7 on 2023-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tennis_atp", "0007_rename_l_1stin_atpmatches_l_firstin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atpmatches",
            name="l_ace",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_bpfaced",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_bpsaved",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_df",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_firstin",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_firstwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_secondwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_svgms",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="l_svpt",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="minutes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_ace",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_bpfaced",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_bpsaved",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_df",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_firstin",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_firstwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_secondwon",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_svgms",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="atpmatches",
            name="w_svpt",
            field=models.IntegerField(null=True),
        ),
    ]
